### ISSUE TITLE
CoreDns and use etcd as a backend (authorization TLS)

### ISSUE THREAD

**Issue by slucheninov** [coredns/helm#144]
Hi.
I'm setting up coredns through the ectd plugin with TLS authorization and ran into a problem:
my values.yaml:
```
isClusterService: false
servers:
- zones:
  - zone: example.com
  port: 53
  plugins:
  - name: reload
  - name: health
    configBlock: |-
      lameduck 5s
  - name: any
  - name: etcd
    configBlock: |-
      path /skydns
      endpoint https://etcd.etcd.svc.cluster.local:2379
      tls /etc/coredns/cert/tls.crt /etc/coredns/cert/tls.key /etc/coredns/cert/ca.crt
extraSecrets:
  - name: etcd-client-tls
    mountPath: /etc/coredns/cert
```
coredns runs as nonroot user this can be seen from the file [Dockerfile](https://github.com/coredns/coredns/blob/master/Dockerfile#L20C1-L20C21)  and secrets are mounted with root rights (chmod 400)
[deployment.yaml](https://github.com/coredns/helm/blob/master/charts/coredns/templates/deployment.yaml#L152)
```
{{- range .Values.extraSecrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }}
            defaultMode: 400 <--- 
{{- end }}
```
Currently, the secret file would still be created with root as the owner. Unless the file is world-readable, the main container process will not be able to read it. So in this scenario (which is not uncommon I would guess), there is little to no use for the defaultMode. Either the secret file needs to be created with the owner of runAsUser or you should be able to explicitly set the owner of the secret file.
