### ISSUE TITLE
Prometheus.service.annotations in the default values.yaml should be unbiased

### ISSUE THREAD

**Issue by den-is** [coredns/helm#157]
Right now default values.yaml set biased annotation on coredns prometheus metrics service object.

```yaml
prometheus:
  service:
    enabled: false
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9153"
```

- default values in the most cases should be blank literals
- current annotations setup is biased, putting this very specific annotations

What if someone does not want to use any scraping at all?
What if someone is not using this native prometheus "hack" and is using prometheus operator workflow with ServiceMonitors?

In both above cases I have to override default value for these annotations with `null` to get completely rid of them.
```yaml
prometheus:
  service:
    enabled: true
    annotations: null
  monitor:
    enabled: true
```

Yep, these annotations won't hurt in most cases, and can be just ignored. But we are returning to the default case. Default values in the chart's values.yaml should be blank.

If a person wants to scrape coredns metrics using these annotations, this person has to explicitly enable annotations for his specific setup. That also makes setup more efficient, explicit, and trackable in GitOps way.

**Comment by hagaibarel** [comment]
I don't see this as biased, it's more of "batteries included but replaceable". We provide sane defaults that fit most use cases with on option to override / change them if the need arises.

**Comment by den-is** [comment]
Another case.
It is hard to override map/list values in helm.

Let's say I want to add annotations to metrics service, and don't want to keep prometheus annotations.

```
prometheus:
  service:
    enabled: true
    annotations:
      testannotation: "test"
```

Helm is merging default map values with user provided values:
So resulting resource will have this annotations:
```yaml
# helm template coredns ./helm/charts/coredns -f ~/projects/kublab/apps/coredns/coredns-values-1.28.2.yaml --dry-run --debug

apiVersion: v1
kind: Service
metadata:
  name: coredns-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "coredns"
    helm.sh/chart: "coredns-1.29.1"
    k8s-app: coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
    app.kubernetes.io/name: coredns
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
    testannotation: test
```

So right no there are two options:
- completely disable annotations for the metrics service with `prometheus.service.annotations=null`
- all have combination of annotations from the default values.yaml and user provided annotations.
