### ISSUE TITLE
Question: How to enable rolling update of coreDNS pods when autoscaler is enabled

### ISSUE THREAD

**Issue by kky-fury** [coredns/helm#170]
Hello all,

I am trying to update `coreDNS` image versions across different Kubernetes clusters.

I am using the helm chart version `1.31.0` with the following relevant values:

```yaml
replicaCount: 6
rollingUpdate:
    maxUnavailable: 1
    maxSurge: 25%
...
autoscaler:
    enabled: true
    min: 4
    max: 100
podDisruptionBudget:
    minAvailable: 1
```

When I do the update all `coreDNS` pods are started at once without respecting the rollingUpdate constraints. I think it might be because of how replicas are defined in `templates/deployment.yaml`:

```yaml
spec:
  {{- if and (not .Values.autoscaler.enabled) (not .Values.hpa.enabled) }}
  replicas: {{ .Values.replicaCount }}
```
Can you please suggest possible methods to do the update while respecting the rolling update constraints in this scenario.

Thank you for the help.
