### ISSUE TITLE
v1.42.1 removes service port

### ISSUE THREAD

**Issue by rwong2888** [coredns/helm#212]
Service "coredns" is invalid: spec.ports: Required value 

<img width="631" alt="Image" src="https://github.com/user-attachments/assets/76352a86-a69c-4d71-bde4-64486f1d0809" />

**Comment by alemairebe** [comment]
to be precise ; the above, is what I get too via ArgoCD but running helm template locally, I get : 
on the service
```
  ports:
  - {"name":"udp-53","port":53,"protocol":"UDP","targetPort":53}
```
and on the pod : 
```
        ports:
        - {"containerPort":53,"name":"udp-53","protocol":"UDP"}
        - {"containerPort":53,"name":"tcp-53","protocol":"TCP"}
        - {"containerPort":9153,"name":"tcp-9153","protocol":"TCP"}
```
which are removed as they do not match the api specification

**Comment by Kariton** [comment]
flux diff on my end:
```diff
--- HelmRelease: kube-system/coredns Service: kube-system/kube-dns

+++ HelmRelease: kube-system/coredns Service: kube-system/kube-dns

@@ -19,12 +19,8 @@

   clusterIP: 10.96.0.10
   ports:
   - name: udp-53
     port: 53
     protocol: UDP
     targetPort: 53
-  - name: tcp-53
-    port: 53
-    protocol: TCP
-    targetPort: 53
   type: ClusterIP
```

values:
```yaml
---
priorityClassName: system-cluster-critical
k8sAppLabelOverride: kube-dns

replicaCount: 2

service:
  name: kube-dns
  clusterIP: 10.96.0.10

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node.kubernetes.io/unschedulable
    operator: Exists
    effect: NoSchedule

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: coredns
```

**Comment by IdlePhysicist** [comment]
Looks to be related to this commit.

https://github.com/coredns/helm/commit/d579bfc7359dba42e9baa2f9b2dd3fc377b51f43

**Comment by Ca-moes** [comment]
On `1.42.1`:
```yaml
# Using:
- zones:
  - zone: .
# Results in
ports:
  - {"name":"udp-53","port":53,"protocol":"UDP","targetPort":53}

# Using 
- zones:
  - zone: .
    scheme: dns://
    use_tcp: true
# Results in
ports:
  - {"name":"udp-53","port":53,"protocol":"UDP","targetPort":53}
  - {"name":"tcp-53","port":53,"protocol":"TCP","targetPort":53}
```

Some changes need to be made to `define "coredns.servicePorts"`: https://github.com/coredns/helm/blob/0aecc93a376617770da3990eab26b7b493feab3f/charts/coredns/templates/_helpers.tpl#L66

Here are the possible changes: https://www.diffchecker.com/OqOaskoR/

**Comment by portswigger-tim** [comment]
Helmfile / Helm gives:

```
Error: UPGRADE FAILED: release scanner-dns failed, and has been rolled back due to atomic being set: cannot patch "scanner-dns-coredns" with kind Service: Service "scanner-dns-coredns" is invalid: spec.ports: Required value
```

Although the diff shows:
```diff
    name: scanner-dns-coredns
    namespace: scanner-dns
    labels:
      app.kubernetes.io/managed-by: "Helm"
      app.kubernetes.io/instance: "scanner-dns"
-     helm.sh/chart: "coredns-1.39.2"
+     helm.sh/chart: "coredns-1.42.1"
      app.kubernetes.io/name: coredns
  spec:
    selector:
      app.kubernetes.io/instance: "scanner-dns"
      app.kubernetes.io/name: coredns
    clusterIP: 172.20.0.20
    ports:
    - {"name":"udp-53","port":53,"protocol":"UDP","targetPort":53}
-   - {"name":"tcp-53","port":53,"protocol":"TCP","targetPort":53}
    type: ClusterIP
```

Perhaps there is somefunkiness with the generated patch and list combination 🤔

**Comment by viceice** [comment]
```yaml
servers:
  - zones:
      - zone: .
        scheme: dns://
        use_tcp: true
    port: 53
```

this doesn't work either, as it's removing all plugins. 😕  now downgrading, i don't want to repeat all those settings from default values.

**Comment by sebastiangaiser** [comment]
> Looks to be related to this commit.
> 
> [d579bfc](https://github.com/coredns/helm/commit/d579bfc7359dba42e9baa2f9b2dd3fc377b51f43)

@hagaibarel @ampls can you please have a look at this as you are part of the "breaking" PR https://github.com/coredns/helm/pull/211 .

**Comment by viceice** [comment]
> > servers:
> > 
> > * zones:
> >   
> >   * zone: .
> >     scheme: dns://
> >     use_tcp: true
> >     port: 53
> >     this doesn't work either, as it's removing all plugins. 😕 now downgrading, i don't want to repeat all those settings from default values.
> 
> [@viceice](https://github.com/viceice) According to your example, you have an extra indent. [`helm/charts/coredns/values.yaml`](https://github.com/coredns/helm/blob/master/charts/coredns/values.yaml#L107-L110)
> 
> servers:
>   - zones:
>     - zone: .
>         scheme: dns://
>         use_tcp: true
>     port: 53
>     servicePort: 53
>     plugins:
>     - name: errors
>     - name: health
>     ...

No, your sample is broken. `zone` is a string, so you can't have a child object there. I've copied the yaml from original values and adapted a little.

**Comment by brianmay** [comment]
If I understand correctly this is now fixed in 1.42.2 thanks to the following change https://github.com/coredns/helm/pull/214

**Comment by brianmay** [comment]
Sorry, I got that wrong, the error persists.

```
Error: UPGRADE FAILED: cannot patch "coredns-cache" with kind Service: Service "coredns-cache" is invalid: spec.ports: Required value
```

**Comment by nkichukov** [comment]
I can confirm we are also getting this error now on all our clusters(via flux2). Our configuration related to this is:

```
    servers:
    - plugins:
      port: 53
      zones:
      - zone: .
```

And this used to work before `v1.42.1`.

**Comment by brianmay** [comment]
I think somebody needs to create a pull request to fix this. That might mean reverting both #211 and #214.

Unfortunately @ampls who contributed the pull requests doesn't appear to be responding.

The original justification comes from #23 though:

> According to [values.yaml](https://github.com/coredns/helm/blob/master/stable/coredns/values.yaml#L130)
dns:// is supposed to be udp only with optional tcp enablement through
use_tcp flag.

I think this wasn't properly tested. And was a breaking change. People may have been expecting that behavior, and not expecting a breaking change to occur in a minor point release.

Turning on the `use_tcp` flag needs to be done for each zone. Does this help work around the issue?

```yaml
    servers:
      zones:
      - zone: .
        use_tcp: true
```

**Comment by ampls** [comment]
It looks like that issue is in the same _helpers.tpl [here] (https://github.com/coredns/helm/blob/master/charts/coredns/templates/_helpers.tpl#L89) and [here](https://github.com/coredns/helm/blob/master/charts/coredns/templates/_helpers.tpl#L160).  If `scheme` not defined nothing brings it to default `dns://`. 
```
From
{{- if has (default "" .scheme) (list "dns://") -}}
TO
{{- if has (default "" .scheme) (list "dns://" "") -}}
```
Could someone check and confirm that it will fix issue, if so I will place PR.
Thanks and sorry for trouble.

**Comment by brianmay** [comment]
I tried this change as above:

```diff
diff --git a/charts/coredns/templates/_helpers.tpl b/charts/coredns/templates/_helpers.tpl
index b86fffd..2c2a9d6 100644
--- a/charts/coredns/templates/_helpers.tpl
+++ b/charts/coredns/templates/_helpers.tpl
@@ -86,7 +86,7 @@ Generate the list of ports automatically from the server definitions
         TCP: tls://, grpc://, https://
         */}}
         {{- range .zones -}}
-            {{- if has (default "" .scheme) (list "dns://") -}}
+            {{- if has (default "" .scheme) (list "dns://" "") -}}
                 {{/* Optionally enable tcp for this service as well */}}
                 {{- if eq (default false .use_tcp) true }}
                     {{- $innerdict := set $innerdict "istcp" true -}}
@@ -157,7 +157,7 @@ Generate the list of ports automatically from the server definitions
         TCP: tls://, grpc://, https://
         */}}
         {{- range .zones -}}
-            {{- if has (default "" .scheme) (list "dns://") -}}
+            {{- if has (default "" .scheme) (list "dns://" "") -}}
                 {{/* Optionally enable tcp for this service as well */}}
                 {{- if eq (default false .use_tcp) true }}
                     {{- $innerdict := set $innerdict "istcp" true -}}
```

But I still get the exact same diff:

```
kube-system, coredns-cache, Service (v1) has changed:
...
    labels:
      app.kubernetes.io/managed-by: "Helm"
      app.kubernetes.io/instance: "coredns-cache"
-     helm.sh/chart: "coredns-1.39.2"
+     helm.sh/chart: "coredns-1.42.3"
      k8s-app: coredns
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: "CoreDNS"
...
    clusterIP: 10.100.100.1
    ports:
    - {"name":"udp-53","port":53,"protocol":"UDP","targetPort":53}
-   - {"name":"tcp-53","port":53,"protocol":"TCP","targetPort":53}
    type: ClusterIP
```

And the exact same error:

```
Error: UPGRADE FAILED: cannot patch "coredns-cache" with kind Service: Service "coredns-cache" is invalid: spec.ports: Required value
```

I am not sure that I understand the error. Seems to be complaining that the value is not supplied to `spec.ports` but that  clearly is still provided. It looks valid YAML to me also.

More importantly, it is still trying to remove the TCP port. That makes this a breaking change IMHO. You don't expect to have major features change like this when upgrading to a new point release (even if it was previously technically broken).

**Comment by brianmay** [comment]
Run the same failed upgrade command two times in the row, and it works.

Thinking this might be because of some weird helm upgrade behavior.  It is acting like helm is trying to patch an empty values for `ports` before supplying the new value, which breaks the schema in the meantime. But only on the first attempt.

**Comment by brianmay** [comment]
I just realized that I have this weird config:

```yaml
servers:
    -
        zones:
            -
                scheme: ""
                use_tcp: ""
                zone: .
```

If I delete this zones, then it works (as is no changes). This might invalidate what I said before about the breaking changes, it probably looks like I am trying to explicitly disable the tcp port. And that wasn't working.

Still a bit weird that helm does the wrong thing.

Based on the comments here though, other people might be having different issues that I can't reproduce.

**Comment by brianmay** [comment]
I think this solves the problem for me:

```diff
diff --git a/charts/coredns/templates/_helpers.tpl b/charts/coredns/templates/_helpers.tpl
index b86fffd..2c2a9d6 100644
--- a/charts/coredns/templates/_helpers.tpl
+++ b/charts/coredns/templates/_helpers.tpl
@@ -86,7 +86,7 @@ Generate the list of ports automatically from the server definitions
         TCP: tls://, grpc://, https://
         */}}
         {{- range .zones -}}
-            {{- if has (default "" .scheme) (list "dns://") -}}
+            {{- if has (default "" .scheme) (list "dns://" "") -}}
                 {{/* Optionally enable tcp for this service as well */}}
                 {{- if eq (default false .use_tcp) true }}
                     {{- $innerdict := set $innerdict "istcp" true -}}
@@ -157,7 +157,7 @@ Generate the list of ports automatically from the server definitions
         TCP: tls://, grpc://, https://
         */}}
         {{- range .zones -}}
-            {{- if has (default "" .scheme) (list "dns://") -}}
+            {{- if has (default "" .scheme) (list "dns://" "") -}}
                 {{/* Optionally enable tcp for this service as well */}}
                 {{- if eq (default false .use_tcp) true }}
                     {{- $innerdict := set $innerdict "istcp" true -}}
diff --git a/charts/coredns/values.yaml b/charts/coredns/values.yaml
index aca59f9..09c3b7d 100644
--- a/charts/coredns/values.yaml
+++ b/charts/coredns/values.yaml
@@ -107,6 +107,7 @@ securityContext:
 servers:
 - zones:
   - zone: .
+    use_tcp: true
   port: 53
   # -- expose the service on a different port
   # servicePort: 5353
```

This explicitly sets the default value of `use_tcp` to the expected value, and the patch from above seems to be required too.

**Comment by IdlePhysicist** [comment]
FYI for everyone, a v1.42.4 release has been made with #217 included. 

https://github.com/coredns/helm/releases/tag/coredns-1.42.4

**Comment by brianmay** [comment]
Looks good to me.

**Comment by AlessandroZanatta** [comment]
I can confirm v1.42.4 solved the issue for me!

**Comment by brianmay** [comment]
@rwong2888 What is the values you are providing? Suspect you have something different to me which is doing this.

**Comment by rwong2888** [comment]
@brianmay here is my values file


```
coredns:
  image:
    repository: forbes-docker.jfrog.io/coredns/coredns
  podAnnotations:
    override-url.version-checker.io/coredns: docker.io/coredns/coredns
    match-regex.version-checker.io/coredns: '(\d+)\.(\d+)\.(\d+)'
  autoscaler:
    enabled: true
    min: 3
    resources:
      requests:
        cpu: "40m"
        memory: "20Mi"
      limits:
        cpu: "40m"
        memory: "20Mi"
  k8sAppLabelOverride: kube-dns
  fullnameOverride: coredns
  podDisruptionBudget:
    minAvailable: 1
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: coredns
    matchLabelKeys:
    - pod-template-hash
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: coredns
    matchLabelKeys:
    - pod-template-hash

  # Default zone is what Kubernetes recommends:
  # https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options
  servers:
  - zones:
    - zone: .
    port: 53
    plugins:
    - name: errors
    # Serves a /health endpoint on :8080, required for livenessProbe
    - name: health
      configBlock: |-
        lameduck 5s
    # Serves a /ready endpoint on :8181, required for readinessProbe
    - name: ready
    # Required to query kubernetes API for data
    - name: kubernetes
      parameters: cluster.local in-addr.arpa ip6.arpa
      configBlock: |-
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    # Serves a /metrics endpoint on :9153, required for serviceMonitor
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: forward
      parameters: . /etc/resolv.conf
    - name: cache
      parameters: 30
    - name: loop
    - name: reload
    - name: loadbalance
    # new stuff
    - name: log
  - zones:
    - zone: forbes.com
    port: 53
    plugins:
    - name: errors
    - name: cache
      parameters: 30
    - name: loop
    - name: forward
      parameters: . 8.8.8.8
    # new stuff
    - name: log
```
