### ISSUE TITLE
proposal: decouple loadbalancer service to two standalone services with the same loadBalancerIP value

### ISSUE THREAD

**Issue by lukasmrtvy** [coredns/helm#26]
Can We decouple loadbalancer service to two standalone services with the same loadBalancerIP value ? Problem is that k8s < 1.20 does not support mixedprotocol in loadbalancer service. There are two options, opt-in alfa feature in k8s>=1.20, or use two standalone services ( one for tcp and other for udp ) with same loadBalancerIP value.

Use case: TCP/UDP DNS external service 

Related: https://github.com/kubernetes/kubernetes/issues/23880

Thanks

**Comment by git-dolia** [comment]
I have the same issue

**Comment by larssb** [comment]
So Mr. @lukasmrtvy,

You can actually accomplish not bumping into the:

```txt
Error: Service "coredns" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"udp-53", Protocol:"UDP", AppProtocol:(*string)(nil), Port:53, TargetPort:intstr.IntOrString{Type:0, IntVal:53, StrVal:""}, NodePort:0}, core.ServicePort{Name:"tcp-53", Protocol:"TCP", AppProtocol:(*string)(nil), Port:53, TargetPort:intstr.IntOrString{Type:0, IntVal:53, StrVal:""}, NodePort:0}}: may not contain more than 1 protocol when type is 'LoadBalancer'
```

err. on newer version of Kubernetes ( k8s >=1.20 ) by ensuring that the zones you configure have the scheme to use set.
E.g.: `scheme: dns://` or to give you the full chunk of the required YAML def. to use:

```yaml
servers:
- zones:
  - zone: .
    scheme: dns://
  port: 53
  plugins:
  - name: errors
  - name: health
    configBlock: |-
      lameduck 5s
  - name: ready
  - name: kubernetes
    parameters: cluster.local in-addr.arpa ip6.arpa
    configBlock: |-
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
      ttl 30
  - name: prometheus
    parameters: 0.0.0.0:9153
  - name: forward
    parameters: . /etc/resolv.conf
  - name: cache
    parameters: 30
  - name: loop
  - name: reload
  - name: loadbalance  
```

---

That does the trick.
> N.B. the docs on this Helm chart actually points to it. See [this section](https://github.com/coredns/helm#caveats)

---

I hope the above helps and makes sense.

Have a great weekend.

> N.B. if this solves your challenge - feel free to close the issue.
