### ISSUE TITLE
Readiness and Liveness probes should be added in coredns-autoscaler deployment 

### ISSUE THREAD

**Issue by skolenkin** [coredns/helm#32]
If the Kubernetes worker node fail coredns-autoscaler pod doesn't re-schedule to another k8s node because coredns-autoscaler doesn't have liveness probes.

```
10.10.128.200 NotReady worker 320d v1.20.6

coredns-autoscaler-6957745d44-tl7w7               1/1     Running     0          57m     172.20.14.23     10.10.128.200
```

Expectations: After added liveness probes Kubernetes scheduler reschedule pod to another node 

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
```

cluster-proportional-autoscaler from version 1.8.0 support simple healthz
https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/releases/tag/1.8.0
https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/blob/1.8.1/pkg/autoscaler/health.go#L62
