### ISSUE TITLE
exposing prometheus metrics through helm chart doesn't work

### ISSUE THREAD

**Issue by rhollins** [coredns/helm#73]
I use the following config file:

```
prometheus:
  service:
    enabled: true
  monitor:
    enabled: true
    additionalLabels:
      release: prometheus
serviceType: "LoadBalancer"
service:
# clusterIP: ""
# externalIPs: []
# externalTrafficPolicy: ""
  # The name of the Service
  # If not set, a name is generated using the fullname template
  name: ""
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
isClusterService: false
```

The service monitor object is being created as well as the metrics service itself but the metrics port/endpoint on pod is not so I cannot reach 
http://<IP>:9153/metrics is showing as down 

I use AKS 1.23.8, helm 3.9 and coredns chart 1.19.2
