### ISSUE TITLE
Indentation issue on ExternalIPs

### ISSUE THREAD

**Issue by reivaxm** [coredns/helm#89]
Hello,
When i use the service as ExternalIPs with multiple ip, the indentation is broken

values sample:
```
---
serviceType: externalIPs
service:
  externalIPs: ['192.168.10.1', '2345:0425:2CA1:50']
```

The generated service look like
```
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-coredns
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "coredns"
    helm.sh/chart: "coredns-1.19.7"
    k8s-app: coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
    app.kubernetes.io/name: coredns
spec:
  selector:
    app.kubernetes.io/instance: "coredns"
    k8s-app: coredns
    app.kubernetes.io/name: coredns
  externalIPs:
      - 192.168.10.1
    - 2345:0425:2CA1:50
  ports:
  - {"name":"udp-53","port":53,"protocol":"UDP"}
  - {"name":"tcp-53","port":53,"protocol":"TCP"}
  type: externalIPs
```
  
  As you can see the external ips have identation issue.
  
  I suppose the issue could be fix by changing the service template line 41 by
  ```
  {{ toYaml .Values.service.externalIPs | nindent 4 }}
  ```
