### ISSUE TITLE
Adopt Helm chart to mimic Amazon EKS CoreDNS naming conventions

### ISSUE THREAD

**Issue by youwalther65** [coredns/helm#97]
I propose to add additional resources to Helm chart to be able to mimic naming conventions of Amazon EKS CoreDNS implementation to quickly move between self-managed CoreDNS, Helm managed CoreDNS and EKS managed ad-on.
Especially the following ressources need name resource

configmap: "coredns"
clusterrole: "system:coredns"
clusterrolebinding": "system:coredns"

In addition all other resources should allow naming without release name prefix.
I already created a fork of the repo, done all the necessary changes and currently testing it on an Amazon EKS cluster.

Please let me know if a corresponding PR has a chance of being considered.

**Comment by youwalther65** [comment]
Sample values.yaml for the proposed change:

```yaml
# placement
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
          - arm64
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values:
            - kube-dns
        topologyKey: kubernetes.io/hostname
      weight: 100
nodeSelector:
  system-component: enabled
tolerations:
- key: system-component
  operator: Equal
  value: enabled
  effect: NoSchedule
podDisruptionBudget:
  maxUnavailable: 1
# use for coredns and autoscaler deployment
priorityClassName: system-cluster-critical
pdb:
  name: "coredns"
autoscaler:
  # Enabled the cluster-proportional-autoscaler
  enabled: true
  # special values from custome Helm chart
  namePrefix: "coredns"
  # placement
  nodeSelector:
    system-component: enabled
  tolerations:
  - key: system-component
    operator: Equal
    value: enabled
    effect: NoSchedule
service:
   name: "kube-dns"
   namespace: kube-system
serviceAccount:
  create: true
  name: "coredns"
  namespace: kube-system
deployment:
  enabled: true
  name: "coredns"
  namespace: kube-system
# kube-prometheus-stack already comes with a working ServiceMonitor "kube-prometheus-stack-coredns" per default
configmap:
  name: "coredns"
clusterrole:
  name: "system:coredns"
clusterrolebinding:
  name: "system:coredns"
servicemonitor:
  name: "coredns"
configmapAutoscaler:
  namePrefix: "coredns"
serviceaccountAutoscaler:
  namePrefix: "coredns"
clusterroleAutoscaler:
  namePrefix: "coredns"
clusterrolebinding-autoscaler:
  name-prefix: "coredns"
serviceaccountAutoscaler:
  namePrefix: "coredns"
servicemetrics:
  namePrefix: "coredns"
```
